apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "greengate.fullname" . }}-admin
  labels:
    app: {{ include "greengate.name" . }}-admin
    chart: {{ include "greengate.chart" . }}
    release: {{ .Release.Name }}
    component: frontend-admin
spec:
  replicas: {{ .Values.replicaCount.admin }}
  selector:
    matchLabels:
      app: {{ include "greengate.name" . }}-admin
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "greengate.name" . }}-admin
        release: {{ .Release.Name }}
        component: frontend-admin
    spec:
      containers:
      - name: admin
        image: "{{ .Values.image.admin.repository }}:{{ .Values.image.admin.tag }}"
        imagePullPolicy: {{ .Values.image.admin.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.admin.targetPort }}
          protocol: TCP
        env:
        - name: VITE_API_URL
          value: {{ .Values.env.admin.VITE_API_URL | quote }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources.admin | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "greengate.fullname" . }}-admin
  labels:
    app: {{ include "greengate.name" . }}-admin
    chart: {{ include "greengate.chart" . }}
    release: {{ .Release.Name }}
    component: frontend-admin
spec:
  type: {{ .Values.service.admin.type }}
  ports:
  - port: {{ .Values.service.admin.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if and (eq .Values.service.admin.type "NodePort") .Values.service.admin.nodePort }}
    nodePort: {{ .Values.service.admin.nodePort }}
    {{- end }}
  selector:
    app: {{ include "greengate.name" . }}-admin
    release: {{ .Release.Name }}