apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "greengate.fullname" . }}-backend
  labels:
    app: {{ include "greengate.name" . }}-backend
    chart: {{ include "greengate.chart" . }}
    release: {{ .Release.Name }}
    component: backend
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      app: {{ include "greengate.name" . }}-backend
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "greengate.name" . }}-backend
        release: {{ .Release.Name }}
        component: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: backend
        image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
        imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.backend.targetPort }}
          protocol: TCP
        env:
        - name: MONGO_URI
          value: "mongodb://{{ include "greengate.fullname" . }}-mongo:27017/greengate"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "greengate.fullname" . }}-secret
              key: jwt-secret
        - name: JWT_EXPIRE
          value: {{ .Values.env.backend.JWT_EXPIRE | quote }}
        - name: PORT
          value: {{ .Values.env.backend.PORT | quote }}
        resources:
          {{- toYaml .Values.resources.backend | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "greengate.fullname" . }}-backend
  labels:
    app: {{ include "greengate.name" . }}-backend
    chart: {{ include "greengate.chart" . }}
    release: {{ .Release.Name }}
    component: backend
spec:
  type: {{ .Values.service.backend.type }}
  ports:
  - port: {{ .Values.service.backend.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if and (eq .Values.service.backend.type "NodePort") .Values.service.backend.nodePort }}
    nodePort: {{ .Values.service.backend.nodePort }}
    {{- end }}
  selector:
    app: {{ include "greengate.name" . }}-backend
    release: {{ .Release.Name }}