apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "greengate.fullname" . }}-user
  labels:
    app: {{ include "greengate.name" . }}-user
    chart: {{ include "greengate.chart" . }}
    release: {{ .Release.Name }}
    component: frontend-user
spec:
  replicas: {{ .Values.replicaCount.user }}
  selector:
    matchLabels:
      app: {{ include "greengate.name" . }}-user
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "greengate.name" . }}-user
        release: {{ .Release.Name }}
        component: frontend-user
    spec:
      containers:
      - name: user
        image: "{{ .Values.image.user.repository }}:{{ .Values.image.user.tag }}"
        imagePullPolicy: {{ .Values.image.user.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.user.targetPort }}
          protocol: TCP
        env:
        - name: VITE_API_URL
          value: {{ .Values.env.user.VITE_API_URL | quote }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources.user | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "greengate.fullname" . }}-user
  labels:
    app: {{ include "greengate.name" . }}-user
    chart: {{ include "greengate.chart" . }}
    release: {{ .Release.Name }}
    component: frontend-user
spec:
  type: {{ .Values.service.user.type }}
  ports:
  - port: {{ .Values.service.user.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if and (eq .Values.service.user.type "NodePort") .Values.service.user.nodePort }}
    nodePort: {{ .Values.service.user.nodePort }}
    {{- end }}
  selector:
    app: {{ include "greengate.name" . }}-user
    release: {{ .Release.Name }}